//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week5_Day4EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_User
    {
        public int MovieId { get; set; }
        public string UserName { get; set; }
    
        public virtual Movy Movy { get; set; }
    }
}
